import { providerMeta as baseMeta, services as baseServices, unused as baseUnused, resources as baseResources, recommendations as baseRecs, trend as baseTrend, type Cloud, type Finding, type Resource, type Recommendation, type Service } from './cloud';

export type ScenarioId = 'baseline' | 'saas' | 'ecommerce' | 'enterprise';
export type Scenario = { id: ScenarioId; name: string; tagline: string; synthetic: boolean; scale: Record<Cloud, number>; growth: number; boost: string[]; unused: Finding[]; resources: Resource[]; recommendations: Recommendation[] };

export const scenarios: Scenario[] = [
  { id: 'baseline', name: 'Acme Production', tagline: 'Your workspace demo data', synthetic: false, scale: { AWS: 1, Azure: 1, GCP: 1 }, growth: 0, boost: [], unused: [], resources: [], recommendations: [] },
  { id: 'saas', name: 'Fast-Growth SaaS', tagline: 'Kubernetes and database sprawl', synthetic: true, scale: { AWS: 1.6, Azure: .7, GCP: 1.9 }, growth: 9, boost: ['Amazon RDS', 'Amazon ECS', 'GKE', 'Cloud SQL', 'Azure Kubernetes'],
    unused: [{ id: 's-u1', name: 'feature-preview-ns-42', provider: 'GCP', service: 'GKE', cost: 418, lastActivity: '16 days ago', status: 'Potentially Unused', evidence: 'Preview namespace has had no ingress traffic for 16 days; 6 pods still running.', action: 'Check with the owning squad before removing the preview environment.', history: [402, 410, 414, 416, 418, 418] }],
    resources: [{ id: 's-r1', name: 'tenant-db-primary', provider: 'AWS', service: 'RDS · db.r6g.4xlarge', cpu: 9.6, memory: 31.2, cost: 1240, savings: 520, recommendation: 'Downsize database class' }, { id: 's-r2', name: 'gke-default-pool', provider: 'GCP', service: 'GKE · e2-standard-16', cpu: 17.8, memory: 26.4, cost: 960, savings: 380, recommendation: 'Enable cluster autoscaling' }],
    recommendations: [{ id: 's-rec1', title: 'Right-size tenant database', provider: 'AWS', resource: 'tenant-db-primary', problem: 'Database class sized for projected growth, not current load.', evidence: 'CPU 9.6% · Memory 31.2% over the last 30 days', savings: 520, priority: 'High', confidence: 91, action: 'Move to db.r6g.2xlarge and monitor connection counts for a week.', cost: 1240 }, { id: 's-rec2', title: 'Enable GKE autoscaling', provider: 'GCP', resource: 'gke-default-pool', problem: 'Node pool runs at fixed size overnight.', evidence: 'CPU 17.8% average · 70% of nodes idle 00:00–07:00', savings: 380, priority: 'High', confidence: 87, action: 'Enable cluster autoscaler with a minimum of 3 nodes.', cost: 960 }] },
  { id: 'ecommerce', name: 'E-commerce Peak Season', tagline: 'Idle capacity after Black Friday', synthetic: true, scale: { AWS: 2.2, Azure: 1.3, GCP: .6 }, growth: 18, boost: ['Amazon EC2', 'CloudFront', 'ElastiCache', 'Virtual Machines', 'App Service'],
    unused: [{ id: 'e-u1', name: 'bf-surge-asg-2025', provider: 'AWS', service: 'Amazon EC2', cost: 1860, lastActivity: '38 days ago', status: 'Low Activity Detected', evidence: 'Surge auto-scaling group still holds 12 instances; request volume dropped 91% since peak.', action: 'Confirm no upcoming campaign before scaling the group down.', history: [6200, 4100, 2600, 1900, 1860, 1860] }],
    resources: [{ id: 'e-r1', name: 'checkout-api-fleet', provider: 'AWS', service: 'EC2 · c6i.4xlarge', cpu: 6.3, memory: 12.8, cost: 2140, savings: 1210, recommendation: 'Scale fleet to baseline' }, { id: 'e-r2', name: 'storefront-app-plan', provider: 'Azure', service: 'App Service · P3v3', cpu: 11.2, memory: 19.5, cost: 870, savings: 410, recommendation: 'Drop to P2v3 tier' }],
    recommendations: [{ id: 'e-rec1', title: 'Scale down post-peak checkout fleet', provider: 'AWS', resource: 'checkout-api-fleet', problem: 'Fleet still sized for peak-season traffic.', evidence: 'CPU 6.3% · Memory 12.8% since the peak ended', savings: 1210, priority: 'High', confidence: 94, action: 'Reduce desired capacity to the pre-season baseline of 4 instances.', cost: 2140 }, { id: 'e-rec2', title: 'Downgrade storefront App Service plan', provider: 'Azure', resource: 'storefront-app-plan', problem: 'Premium plan capacity exceeds normal traffic.', evidence: 'CPU 11.2% · Memory 19.5% over the last 30 days', savings: 410, priority: 'Medium', confidence: 85, action: 'Move to P2v3 and schedule a scale-up ahead of the next campaign.', cost: 870 }] },
  { id: 'enterprise', name: 'Enterprise Multi-Region', tagline: 'Orphaned disks and cross-region egress', synthetic: true, scale: { AWS: 3.1, Azure: 2.6, GCP: 1.4 }, growth: 4, boost: ['Amazon S3', 'Blob Storage', 'Cloud Storage', 'Azure SQL Database'],
    unused: [{ id: 'n-u1', name: 'orphaned-disks-westeurope', provider: 'Azure', service: 'Managed Disks', cost: 940, lastActivity: '74 days ago', status: 'Potentially Unused', evidence: '23 managed disks are not attached to any VM; snapshots exist for 19 of them.', action: 'Verify snapshot coverage and owner tags before deleting unattached disks.', history: [940, 940, 940, 940, 940, 940] }, { id: 'n-u2', name: 'dr-replica-ap-south-1', provider: 'AWS', service: 'Amazon S3', cost: 1320, lastActivity: '60 days ago', status: 'Review Recommended', evidence: 'Cross-region replication target with no reads in 60 days.', action: 'Confirm disaster-recovery requirements before changing the replication rule.', history: [1180, 1220, 1260, 1290, 1310, 1320] }],
    resources: [{ id: 'n-r1', name: 'erp-sql-mi-eastus', provider: 'Azure', service: 'SQL Managed Instance', cpu: 14.1, memory: 33.7, cost: 3280, savings: 1150, recommendation: 'Reduce vCores 16 → 8' }],
    recommendations: [{ id: 'n-rec1', title: 'Clean up unattached managed disks', provider: 'Azure', resource: 'orphaned-disks-westeurope', problem: 'Disks remain billed after their VMs were removed.', evidence: '23 unattached disks · Last attached 74 days ago', savings: 940, priority: 'High', confidence: 90, action: 'Confirm snapshots, then delete disks with no owner response after 7 days.', cost: 940 }, { id: 'n-rec2', title: 'Reduce cross-region egress', provider: 'AWS', resource: 'dr-replica-ap-south-1', problem: 'Replication traffic costs exceed the bucket storage cost.', evidence: '$1,320/month storage · $2,050/month transfer', savings: 1600, priority: 'Medium', confidence: 78, action: 'Limit replication to critical prefixes after DR review.', cost: 3370 }] },
];

export type Dataset = ReturnType<typeof buildDataset>;
export function buildDataset(id: ScenarioId) {
  const s: Scenario = scenarios.find(x => x.id === id) ?? scenarios[0]!;
  const r = (n: number) => Math.round(n);
  const providerMeta = Object.fromEntries((Object.keys(baseMeta) as Cloud[]).map(c => { const m = baseMeta[c]; return [c, { ...m, total: r(m.total * s.scale[c]), average: r(m.average * s.scale[c]), serviceCount: r(m.serviceCount * Math.max(1, s.scale[c] * .8)), change: +(m.change + s.growth).toFixed(1) }]; })) as typeof baseMeta;
  const services = Object.fromEntries((Object.keys(baseServices) as Cloud[]).map(c => [c, baseServices[c].map(x => { const b = s.boost.includes(x.name) ? 1.8 : 1; return { ...x, cost: r(x.cost * s.scale[c] * b), change: +(x.change + (b > 1 ? s.growth : s.growth / 3)).toFixed(1) }; }).sort((a, b) => b.cost - a.cost)])) as Record<Cloud, Service[]>;
  const trend = baseTrend.map(t => ({ ...t, AWS: r(t.AWS * s.scale.AWS), Azure: r(t.Azure * s.scale.Azure), GCP: r(t.GCP * s.scale.GCP) }));
  return { scenario: s, providerMeta, services, trend, unused: [...s.unused, ...baseUnused], resources: [...s.resources, ...baseResources], recommendations: [...s.recommendations, ...baseRecs] };
}
