/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CostUsageRouteImport } from './routes/cost-usage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LowUtilizationRouteImport } from './routes/low-utilization'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UnusedServicesRouteImport } from './routes/unused-services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CostUsageRoute = CostUsageRouteImport.update({
  id: '/cost-usage',
  path: '/cost-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LowUtilizationRoute = LowUtilizationRouteImport.update({
  id: '/low-utilization',
  path: '/low-utilization',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UnusedServicesRoute = UnusedServicesRouteImport.update({
  id: '/unused-services',
  path: '/unused-services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cost-usage': typeof CostUsageRoute
  '/login': typeof LoginRoute
  '/low-utilization': typeof LowUtilizationRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/unused-services': typeof UnusedServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cost-usage': typeof CostUsageRoute
  '/login': typeof LoginRoute
  '/low-utilization': typeof LowUtilizationRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/unused-services': typeof UnusedServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cost-usage': typeof CostUsageRoute
  '/login': typeof LoginRoute
  '/low-utilization': typeof LowUtilizationRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/unused-services': typeof UnusedServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cost-usage'
    | '/login'
    | '/low-utilization'
    | '/recommendations'
    | '/register'
    | '/unused-services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cost-usage'
    | '/login'
    | '/low-utilization'
    | '/recommendations'
    | '/register'
    | '/unused-services'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cost-usage'
    | '/login'
    | '/low-utilization'
    | '/recommendations'
    | '/register'
    | '/unused-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CostUsageRoute: typeof CostUsageRoute
  LoginRoute: typeof LoginRoute
  LowUtilizationRoute: typeof LowUtilizationRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  UnusedServicesRoute: typeof UnusedServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-usage': {
      id: '/cost-usage'
      path: '/cost-usage'
      fullPath: '/cost-usage'
      preLoaderRoute: typeof CostUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/low-utilization': {
      id: '/low-utilization'
      path: '/low-utilization'
      fullPath: '/low-utilization'
      preLoaderRoute: typeof LowUtilizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unused-services': {
      id: '/unused-services'
      path: '/unused-services'
      fullPath: '/unused-services'
      preLoaderRoute: typeof UnusedServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CostUsageRoute: CostUsageRoute,
  LoginRoute: LoginRoute,
  LowUtilizationRoute: LowUtilizationRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  UnusedServicesRoute: UnusedServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
