from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, status, Query
from motor.motor_asyncio import AsyncIOMotorDatabase
from bson import ObjectId
from typing import List, Optional, Dict, Any

from app.db.mongodb import get_database
from app.core.dependencies import get_current_user
from app.schemas.finding import FindingSchema, FindingStatusUpdateSchema
from app.rule_engine.engine import RuleEngine

router = APIRouter(prefix="/findings", tags=["Findings & Evidence"])

@router.post("/generate", response_model=Dict[str, Any])
async def generate_findings_from_db_rules(
    current_user: dict = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database)
):
    """
    Fetch active rules from MongoDB `rules` collection, evaluate all resources,
    upsert findings in MongoDB `findings`, prune stale findings, and return summary.
    """
    engine = RuleEngine(db)
    return await engine.evaluate_all_for_user(current_user["id"])

@router.get("", response_model=List[FindingSchema])
async def list_findings(
    provider: Optional[str] = Query(None),
    severity: Optional[str] = Query(None),
    finding_status: Optional[str] = Query(None, alias="status"),
    rule_id: Optional[str] = Query(None),
    current_user: dict = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database)
):
    """List findings generated by the Rule Engine with evidence and savings."""
    query = {"user_id": current_user["id"]}
    if provider:
        query["provider"] = provider.lower()
    if severity:
        query["severity"] = severity.lower()
    if finding_status:
        query["status"] = finding_status.lower()
    if rule_id:
        query["rule_id"] = rule_id

    cursor = db.findings.find(query).sort("created_at", -1)
    findings = await cursor.to_list(length=500)
    out = []
    for f in findings:
        f["id"] = str(f.pop("_id", ""))
        out.append(FindingSchema(**f))
    return out

@router.get("/{finding_id}", response_model=FindingSchema)
async def get_finding(
    finding_id: str,
    current_user: dict = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database)
):
    """Fetch finding detail view with evidence payload."""
    try:
        f = await db.findings.find_one({
            "_id": ObjectId(finding_id),
            "user_id": current_user["id"]
        })
    except Exception:
        f = await db.findings.find_one({
            "_id": finding_id,
            "user_id": current_user["id"]
        })

    if not f:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Finding not found")

    f["id"] = str(f.pop("_id", ""))
    return FindingSchema(**f)

@router.patch("/{finding_id}", response_model=FindingSchema)
async def update_finding_status(
    finding_id: str,
    update_in: FindingStatusUpdateSchema,
    current_user: dict = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database)
):
    """Update finding status (e.g. approve, snooze, dismiss, resolve)."""
    filter_q = {"user_id": current_user["id"]}
    try:
        filter_q["_id"] = ObjectId(finding_id)
    except Exception:
        filter_q["_id"] = finding_id

    update_doc = {
        "$set": {
            "status": update_in.status.lower(),
            "updated_at": datetime.utcnow()
        }
    }
    if update_in.notes:
        update_doc["$set"]["notes"] = update_in.notes

    res = await db.findings.find_one_and_update(
        filter_q,
        update_doc,
        return_document=True
    )

    if not res:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Finding not found")

    res["id"] = str(res.pop("_id", ""))
    return FindingSchema(**res)
