from fastapi import APIRouter, Depends, HTTPException, status, Query
from motor.motor_asyncio import AsyncIOMotorDatabase
from bson import ObjectId
from typing import List, Optional

from app.db.mongodb import get_database
from app.core.dependencies import get_current_user
from app.schemas.finding import FindingSchema

router = APIRouter(prefix="/findings", tags=["Findings & Evidence"])

@router.get("", response_model=List[FindingSchema])
async def list_findings(
    provider: Optional[str] = Query(None),
    severity: Optional[str] = Query(None),
    finding_status: Optional[str] = Query(None, alias="status"),
    rule_id: Optional[str] = Query(None),
    current_user: dict = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database)
):
    """List findings generated by the Rule Engine with evidence and savings."""
    query = {"user_id": current_user["id"]}
    if provider:
        query["provider"] = provider.lower()
    if severity:
        query["severity"] = severity
    if finding_status:
        query["status"] = finding_status
    if rule_id:
        query["rule_id"] = rule_id

    cursor = db.findings.find(query)
    findings = await cursor.to_list(length=500)
    out = []
    for f in findings:
        f["id"] = str(f["_id"])
        out.append(FindingSchema(**f))
    return out

@router.get("/{finding_id}", response_model=FindingSchema)
async def get_finding(
    finding_id: str,
    current_user: dict = Depends(get_current_user),
    db: AsyncIOMotorDatabase = Depends(get_database)
):
    """Fetch finding detail view with evidence payload."""
    try:
        f = await db.findings.find_one({
            "_id": ObjectId(finding_id),
            "user_id": current_user["id"]
        })
    except Exception:
        f = await db.findings.find_one({
            "_id": finding_id,
            "user_id": current_user["id"]
        })

    if not f:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Finding not found")

    f["id"] = str(f["_id"])
    return FindingSchema(**f)
